import type { Metadata } from "next";
import "./globals.css";
import '../public/css/custom.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from "./theme";
import Header from '@/components/layouts/Header'
import Footer from "@/components/layouts/Footer";
import AppClientLayer from "@/components/layouts/AppClientLayer";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['vietnamese'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <AppClientLayer>
            {children}
            </AppClientLayer>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
